# Generated by Django 4.1.4 on 2022-12-25 18:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FirstApp',
            fields=[
                ('title', models.CharField(max_length=200)),
                ('desc', models.TextField(blank=True, max_length=2000, null=True)),
                ('link', models.CharField(blank=True, max_length=2000, null=True)),
                ('createAt', models.DateField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
