# Generated by Django 4.1.4 on 2023-01-03 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_tag_firstapp_vote_ratio_firstapp_vote_total_review_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='firstapp',
            name='img',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to=''),
        ),
    ]
