# Generated by Django 4.1.4 on 2023-01-06 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('firstapp', '0003_firstapp_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='firstapp',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.profile'),
        ),
    ]
